### ISSUE TITLE
t/010main-unzip.t fails

### ISSUE THREAD

**Issue by eserte** [pmqs/Archive-Zip-SimpleZip#7] opened 2019-11-09 09:09 UTC
On some smoker systems t/010main-unzip.t fails. Sample reports may be seen here: http://matrix.cpantesters.org/?dist=Archive-Zip-SimpleZip%200.029

A pattern is not visible for me. From my smokers I see some test failures on centos7, fedora28, freebsd12, but there are also passes on these systems with different perl versions. It passes on all of my debian and ubuntu systems, but it fails on Andreas' debian/sid smoker: http://www.cpantesters.org/cpan/report/85f214ce-025c-11ea-a69d-87f2a4f3b5ea

In some reports the following is logged:
```
# Uncompression Error: Memory usage limit was reached
```
Indeed, my smoker run with a memory limit of 1 GB (which should be plenty in most situations). But even if I remove the limit, the test is failing.

A strace log is also not helpful.

**Comment by pmqs** [comment] 2019-11-09 10:09
Thanks Slaven,

the issue is triggered by  a memory leak in the LZMA library that [Compress-Raw-Lzma](https://github.com/pmqs/Compress-Raw-Lzma) uses. I've created ticket https://github.com/pmqs/Compress-Raw-Lzma/issues/1 to track it.  

I think Valgrind has found the leak, so just need to test & see if it sorts out this particular issue.

Given what you are saying about  the 1GB limit on some of the smokers, it remains to be seen if that will be enough to fix the out-of-memory errors. LZMA likes to use a lot of memory.

**Comment by pmqs** [comment] 2020-09-16 21:45
Closing - not seen this issue is ages.

**Closed as completed by pmqs** 2020-09-16 21:45 UTC
Labels: duplicate
